### PR TITLE
Fixes issues #30 - 31

### PR DESCRIPTION
**Pull request by mperrien**

### CODE REVIEW

**Comment by antoviaque** [comment]
Thanks! I'm adding deploying this to our list of tasks for the next sprint (ie next week).

**Comment by smarnach** [comment]
Since we have to deploy for a different reason anyway, I'm including this update now.

**Comment by smarnach** [comment]
We didn't go ahead with the deployment for now, but will probably include this tomorrow.

**Comment by smarnach** [comment]
The new version is now only on http://stage.mooc.rue89.com/.  We will deploy to production later today.

**Pull request merged**
